//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDBAOTRI
    {
        public string NDBT_ID { get; set; }
        public string NDBT_ND { get; set; }
        public int NDBT_CHIPHI { get; set; }
        public System.DateTime NDBT_NGAYBT { get; set; }
        public string TTX_BSX { get; set; }
    
        public virtual TTXE TTXE { get; set; }
    }
}
