//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class THUEXE_Entities : DbContext
    {
        public THUEXE_Entities()
            : base("name=THUEXE_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETTHUE> CHITIETTHUEs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DONGIAQG> DONGIAQGs { get; set; }
        public virtual DbSet<HANGSX> HANGSXes { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIXE> LOAIXEs { get; set; }
        public virtual DbSet<NDBAOTRI> NDBAOTRIs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<TTXE> TTXEs { get; set; }
    
        public virtual int deleteTTXE(string tTX_BSX)
        {
            var tTX_BSXParameter = tTX_BSX != null ?
                new ObjectParameter("TTX_BSX", tTX_BSX) :
                new ObjectParameter("TTX_BSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteTTXE", tTX_BSXParameter);
        }
    
        public virtual int insertTTXE(string tTX_BSX, string lX_ID, string hSX_ID, string tTX_DONGIA)
        {
            var tTX_BSXParameter = tTX_BSX != null ?
                new ObjectParameter("TTX_BSX", tTX_BSX) :
                new ObjectParameter("TTX_BSX", typeof(string));
    
            var lX_IDParameter = lX_ID != null ?
                new ObjectParameter("LX_ID", lX_ID) :
                new ObjectParameter("LX_ID", typeof(string));
    
            var hSX_IDParameter = hSX_ID != null ?
                new ObjectParameter("HSX_ID", hSX_ID) :
                new ObjectParameter("HSX_ID", typeof(string));
    
            var tTX_DONGIAParameter = tTX_DONGIA != null ?
                new ObjectParameter("TTX_DONGIA", tTX_DONGIA) :
                new ObjectParameter("TTX_DONGIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertTTXE", tTX_BSXParameter, lX_IDParameter, hSX_IDParameter, tTX_DONGIAParameter);
        }
    
        public virtual ObjectResult<showHANGSX_Result> showHANGSX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showHANGSX_Result>("showHANGSX");
        }
    
        public virtual ObjectResult<showLOAIXE_Result> showLOAIXE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showLOAIXE_Result>("showLOAIXE");
        }
    
        public virtual ObjectResult<showTTXE_Result> showTTXE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showTTXE_Result>("showTTXE");
        }
    
        public virtual int updateTTXE(string tTX_BSX, string tTX_DONGIA)
        {
            var tTX_BSXParameter = tTX_BSX != null ?
                new ObjectParameter("TTX_BSX", tTX_BSX) :
                new ObjectParameter("TTX_BSX", typeof(string));
    
            var tTX_DONGIAParameter = tTX_DONGIA != null ?
                new ObjectParameter("TTX_DONGIA", tTX_DONGIA) :
                new ObjectParameter("TTX_DONGIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTTXE", tTX_BSXParameter, tTX_DONGIAParameter);
        }

    }
}
