//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTXE()
        {
            this.CHITIETTHUEs = new HashSet<CHITIETTHUE>();
            this.NDBAOTRIs = new HashSet<NDBAOTRI>();
        }
    
        public string TTX_BSX { get; set; }
        public string LX_ID { get; set; }
        public string HSX_ID { get; set; }
        public string DONGIA { get; set; }
        public string TTX_TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTHUE> CHITIETTHUEs { get; set; }
        public virtual HANGSX HANGSX { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NDBAOTRI> NDBAOTRIs { get; set; }
    }
}
